### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by TahenyBELGUITH** [TahenyBELGUITH/rails-group-project#8]
in this milestone we : 
- set up the kanban board: https://github.com/users/TahenyBELGUITH/projects/11/views/1?layout=board
-  assign the roles: 
    - student A => @Sevenpros 
    -  student B => @TahenyBELGUITH 

a code reviewer is appreciated  😄 
@Sevenpros @TahenyBELGUITH

**Comment by Davidosky007** [comment]
Hi @TahenyBELGUITH @Sevenpros 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* All team members' information provided 👍 
* Link to project works correctly 👍 

## Required Changes ♻️
* Kindly Open the GitHub project (Kanban board) in your team repo (set up the same columns as in previous group projects). currently, your board is missing the columns 

> To Do
> In Progress
> In Review
> Done
> 
And the cards should look like this as in previous group projects 
![image](https://user-images.githubusercontent.com/52497246/201618069-058b79cd-049d-4f2d-a78d-324bbca47725.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sevenpros** [comment]
@Davidosky007 thanks very much for the reviews, we would like to confirm that we did the kanboard exactly the same as the previous projects with columns as it appears in the provided screenshot below: 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/26649756/201620517-17829b50-7c19-4c25-a763-1c4456cab6c5.png">

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- You've made great changes, however, you need to rename the columns as pointed out by the previous reviewer.

![image](https://user-images.githubusercontent.com/27709832/201630143-59241aca-eed1-4a07-9c04-648bc68fc32d.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
